CREATE TABLE CARS
(
    ID BIGSERIAL NOT NULL,
    MAKE VARCHAR(255),
    MODEL VARCHAR(255),
    MANUFACTUREYEAR INT,
    PRIMARY KEY (id)
);

INSERT INTO CARS(MAKE, MODEL, MANUFACTUREYEAR) VALUES('Chevrolet', 'Tahoe', 2013);
INSERT INTO CARS(MAKE, MODEL, MANUFACTUREYEAR) VALUES('Volkswagen', 'Tiguan', 2014);
